services:
  kafka:
    image: "apache/kafka:3.7.0"
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9997

  connect:
    build:
      context: connect
    hostname: connect
    container_name: connect
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - kafka
    environment:
      CONNECT_GROUP_ID: 123
      CONNECT_STATUS_STORAGE_TOPIC: my-connect-statuses
      CONNECT_CONFIG_STORAGE_TOPIC: my-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: my-connect-offsets
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_REST_HOST_NAME: connect
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components
      LOG_LEVEL: INFO
      JMX_PORT: 9997

  kafka-ui:
    image: "provectuslabs/kafka-ui"
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: Docker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: Debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083

  lenses:
    image: lensesio/lenses
    hostname: lenses
    container_name: lenses
    environment:
      LENSES_PORT: 9991
      LENSES_SECURITY_USER: admin
      LENSES_SECURITY_PASSWORD: admin
    ports:
      - 9991:9991
      - 9102:9102
  
  # mysql:
  #   image: "mysql:8.4.0"
  #   hostname: mysql
  #   container_name: mysql
  #   command: ["mysqld", "--mysql-native-password=ON"]
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_USER: "debezium"
  #     MYSQL_PASSWORD: "password"
  #     MYSQL_DATABASE: "exampledb"
  #     MYSQL_ROOT_HOST: "%"
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
      